// types/Animal.ts
export interface Animal {
    id: string;
    name: string;
    type: string;
    breed: string;
    gender: "male" | "female" | "unknown";
    status: "needs_help" | "looking_for_home" | "adopted";
    location: string;
    images: string[];
    description: string;
    dateAdded: string;
    birthDate: string;
    arrivalDate: string;
    lastOwner?: string;
    source: "stray" | "shelter" | "person";
    color: string;
    height: string;
    weight: string;
    healthStatus: string;
    phoneNumber: string;
    shelterAddress: string;
    state?: string;
    city?: string;
    street?: string;
    zipCode?: string;
    speciesName?: string;
    breedName?: string;
    arriveDate?: string;
    sex?: string;
    isSpayedNeutered?: boolean;
    isVaccinated?: boolean;
    lastVaccinationDate?: string;
    hasChronicDiseases?: boolean;
    medicalNotes?: string;
    requiresSpecialDiet?: boolean;
    hasAllergies?: boolean;
    aggressionLevel?: number;
    friendliness?: number;
    activityLevel?: number;
    goodWithKids?: boolean;
    goodWithPeople?: boolean;
    goodWithOtherAnimals?: boolean;
}
